// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ZGmOEbqK90ak2JXfm3jdSme-nyq4s-w',
    appId: '1:281076734424:web:76198ceb928ea7008d7aad',
    messagingSenderId: '281076734424',
    projectId: 'neynote-ab1cc',
    authDomain: 'neynote-ab1cc.firebaseapp.com',
    storageBucket: 'neynote-ab1cc.firebasestorage.app',
    measurementId: 'G-HPSKRLX72C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNi5iwtwKOmwjZjJmQjNFj67Yc2hImEto',
    appId: '1:281076734424:android:df7523d5db0881008d7aad',
    messagingSenderId: '281076734424',
    projectId: 'neynote-ab1cc',
    storageBucket: 'neynote-ab1cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYn0eNGTZy2mFum7GbbbinrsmdE4gfrn0',
    appId: '1:281076734424:ios:fc9cbec6623a399e8d7aad',
    messagingSenderId: '281076734424',
    projectId: 'neynote-ab1cc',
    storageBucket: 'neynote-ab1cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYn0eNGTZy2mFum7GbbbinrsmdE4gfrn0',
    appId: '1:281076734424:ios:fc9cbec6623a399e8d7aad',
    messagingSenderId: '281076734424',
    projectId: 'neynote-ab1cc',
    storageBucket: 'neynote-ab1cc.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ZGmOEbqK90ak2JXfm3jdSme-nyq4s-w',
    appId: '1:281076734424:web:866666d9e40cb3a08d7aad',
    messagingSenderId: '281076734424',
    projectId: 'neynote-ab1cc',
    authDomain: 'neynote-ab1cc.firebaseapp.com',
    storageBucket: 'neynote-ab1cc.firebasestorage.app',
    measurementId: 'G-FPJ1652PSL',
  );

}